name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Simulasi Proses Build & Test
        run: |
          echo "Memulai proses build dan testing aplikasi..."
          echo "Proses simulasi selesai!"

      - name: Kirim Laporan Manual ke Coralogix
        run: |
          curl -X POST "https://api.ap3.coralogix.com/api/v1/logs" \
          -H "Content-Type: application/json" \
          -H "private_key: ${{ secrets.CORALOGIX_API_KEY }}" \
          -d '{
            "applicationName": "Belajar_CICD",
            "subsystemName": "GitHub_Actions",
            "computerName": "github-runner",
            "logEntries": [
              {
                "timestamp": 0,
                "severity": 3,
                "text": "Status: BERHASIL TERHUBUNG KE CORALOGIX"
              }
            ]
          }'
