name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Simulasi Proses Build & Test
        run: |
          echo "Memulai proses build dan testing aplikasi..."
          echo "Proses simulasi selesai!"

      - name: Kirim Laporan Manual ke Coralogix
        run: |
          curl -X POST "https://ingress.ap3.coralogix.com/logs/v1/singles" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.CORALOGIX_API_KEY }}" \
          -d "[{
            \"applicationName\": \"Belajar_CICD\",
            \"subsystemName\": \"GitHub_Actions\",
            \"computerName\": \"github-runner\",
            \"timestamp\": $(date +%s%3N),
            \"severity\": 3,
            \"text\": \"Status: SUKSES. Proses CI/CD berhasil berjalan di repositori.\"
          }]"
